// FP2 Quest exam readiness modes
(function(){
const HOT={A:new Set([2,3,4,5,6,9]),B:new Set([2,3,4,5]),C:new Set([2,3,4,5,8,9,10,11]),D:new Set([1,2,3,4,5,6,7,9,12,14]),E:new Set([0,1,2,3,4,5,7]),F:new Set([1,2,3,4,5,7,8,9])};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const unique=()=>{const m=new Map();questions.forEach(q=>{const key=q.id+'|'+q.q;if(!m.has(key))m.set(key,q)});return [...m.values()]};
const hot=q=>HOT[q.d]?.has(q.s);
let exam=null;
function balanced60(){let out=[];for(const d of ['A','B','C','D','E','F'])out.push(...shuffle(unique().filter(q=>q.d===d)).slice(0,10));return shuffle(out)}
function startMode(kind){const pool=unique();const qs=kind==='hot'?shuffle(pool.filter(hot)).slice(0,60):balanced60();exam={kind,qs,i:0,score:0,answers:[],locked:false};route={page:'fpExam'};render()}
function examRender(){if(!exam)return go('home');if(exam.i>=exam.qs.length)return resultRender();const q=exam.qs[exam.i];const title=exam.kind==='hot'?'🔥 頻出60問':'📝 60問模試';document.getElementById('app').innerHTML=shell(`<div class="head"><button class="back" onclick="go('home')">×</button><div><b>${title}</b><div class="muted">${exam.i+1}/${exam.qs.length}・${q.id}</div></div></div><div class="card"><span class="tag">${hot(q)?'★★★★★ 頻出重点・':''}法令基準 ${q.law||'2026-04-01'}</span><div class="q">${q.q}</div>${q.c.map((c,i)=>`<button id="ex${i}" class="choice" onclick="fpExamAnswer(${i})">${i+1}. ${c}</button>`).join('')}<button id="exu" class="choice" onclick="fpExamAnswer(-1)">？ わからない</button><div id="exfb"></div></div>`)}
function resultRender(){const n=exam.qs.length,score=exam.score,rate=Math.round(score/n*100),pass=score>=36,target=score>=48;document.getElementById('app').innerHTML=shell(`<h2>${exam.kind==='hot'?'🔥 頻出60問':'📝 60問模試'} 結果</h2><div class="card"><div style="font-size:34px;font-weight:900">${score}/${n}問</div><div class="muted">正答率 ${rate}%</div><p><b>${target?'🏆 8割到達':pass?'✅ 合格基準クリア':'📚 合格基準まであと'+(36-score)+'問'}</b></p><div class="bar"><i style="width:${rate}%"></i></div><p class="muted">本試験の学科合格基準は36/60。FP2 Questでは余裕を持たせて48/60を安定目標にします。</p></div><button class="btn primary" onclick="${exam.kind==='hot'?'startFP2Hot()':'startFP2Mock()'}">もう一度</button><button class="btn" onclick="go('home')">ホームへ</button>`)}
window.fpExamAnswer=function(i){if(!exam||exam.locked)return;exam.locked=true;const q=exam.qs[exam.i],ok=i===q.a;if(ok)exam.score++;exam.answers.push({id:q.id,ok});q.c.forEach((_,x)=>{const el=document.getElementById('ex'+x);if(el){el.disabled=true;if(x===q.a)el.classList.add('good');if(x===i&&i!==q.a)el.classList.add('bad')}});const u=document.getElementById('exu');if(u)u.disabled=true;document.getElementById('exfb').innerHTML=`<div class="card" style="box-shadow:none;background:${ok?'#f0fdf4':'#fef2f2'}"><b>${ok?'○ 正解':'× 不正解'}</b><p>${q.e}</p><button class="btn primary" onclick="fpExamNext()">${exam.i+1===exam.qs.length?'結果を見る':'次の問題へ →'}</button></div>`};
window.fpExamNext=function(){if(!exam)return;exam.i++;exam.locked=false;examRender()};
window.startFP2Mock=()=>startMode('mock');
window.startFP2Hot=()=>startMode('hot');
function addHomeButtons(){const app=document.getElementById('app');if(!app||route.page!=='home'||document.getElementById('examTools'))return;const sec=app.querySelector('.section');if(!sec)return;const box=document.createElement('div');box.id='examTools';box.innerHTML=`<div class="section">🎯 合格仕上げ</div><button class="btn primary" onclick="startFP2Mock()">📝 60問模試 <div class="muted" style="color:#dbeafe">6分野×10問・36/60合格、48/60を目標</div></button><button class="btn" onclick="startFP2Hot()">🔥 頻出60問だけ解く <div class="muted">年金・保険・金融・税・不動産・相続の重点範囲</div></button>`;sec.parentNode.insertBefore(box,sec)}
window.addEventListener('load',()=>{const base=render;render=function(){if(route.page==='fpExam')return examRender();base();addHomeButtons()};render()});
})();