// Pack 13: 頻出計算・数値問題の反復ドリル。既存問題と合わせて総数700問になるまで自動生成する。
(function(){
const arrays=[typeof extraQuestions!=='undefined'?extraQuestions:[],typeof extraQuestions2!=='undefined'?extraQuestions2:[],typeof extraQuestions3!=='undefined'?extraQuestions3:[],typeof extraQuestions4!=='undefined'?extraQuestions4:[],typeof extraQuestions5!=='undefined'?extraQuestions5:[],typeof extraQuestions6!=='undefined'?extraQuestions6:[],typeof extraQuestions7!=='undefined'?extraQuestions7:[],typeof extraQuestions8!=='undefined'?extraQuestions8:[]];
let total=7+arrays.reduce((n,a)=>n+a.length,0), seq=1;
const law='2026-04-01';
const add=q=>{q.id='DRILL-'+String(seq++).padStart(4,'0');q.law=law;extraQuestions8.push(q);total++;};
while(total<700){
 const n=seq, t=(n-1)%20;
 if(t===0){let eps=80+(n%8)*20,per=10+(n%6)*2,price=eps*per;add({d:'C',s:4,q:`株価${price.toLocaleString()}円、EPS${eps}円の株式のPERはいくらか。`,c:[`${per}倍`,`${per+5}倍`,`${Math.max(1,per-5)}倍`,`${per*2}倍`],a:0,e:`PER＝株価÷EPS＝${price.toLocaleString()}÷${eps}＝${per}倍です。`,k:'PER計算'});}
 else if(t===1){let bps=800+(n%6)*200,pbr=[1.2,1.5,1.8,2][n%4],price=Math.round(bps*pbr);add({d:'C',s:4,q:`株価${price.toLocaleString()}円、BPS${bps.toLocaleString()}円の株式のPBRはいくらか。`,c:[`${pbr}倍`,`${(pbr+0.5).toFixed(1)}倍`,`${Math.max(.5,pbr-.5).toFixed(1)}倍`,`${(pbr*2).toFixed(1)}倍`],a:0,e:`PBR＝株価÷BPS＝${price.toLocaleString()}÷${bps.toLocaleString()}＝${pbr}倍です。`,k:'PBR計算'});}
 else if(t===2){let equity=2000+(n%5)*1000,roe=[5,8,10,12][n%4],profit=equity*roe/100;add({d:'C',s:4,q:`自己資本${equity.toLocaleString()}万円、当期純利益${profit.toLocaleString()}万円の場合、ROEはいくらか。`,c:[`${roe}％`,`${roe+5}％`,`${Math.max(1,roe-3)}％`,`${roe*2}％`],a:0,e:`ROE＝当期純利益÷自己資本×100＝${profit.toLocaleString()}÷${equity.toLocaleString()}×100＝${roe}％です。`,k:'ROE計算'});}
 else if(t===3){let price=1000+(n%5)*500,y=[2,3,4,5][n%4],div=price*y/100;add({d:'C',s:4,q:`株価${price.toLocaleString()}円、1株当たり年間配当金${div}円の場合、配当利回りはいくらか。`,c:[`${y}％`,`${y+2}％`,`${Math.max(1,y-1)}％`,`${y*2}％`],a:0,e:`配当利回り＝配当金÷株価×100＝${div}÷${price.toLocaleString()}×100＝${y}％です。`,k:'配当利回り'});}
 else if(t===4){let face=[100,200,300,500][n%4],rate=[1,1.5,2,2.5][n%4],interest=face*rate/100;add({d:'C',s:3,q:`額面${face}万円、表面利率${rate}％の債券の年間利子はいくらか。`,c:[`${interest}万円`,`${interest*2}万円`,`${face*rate/10}万円`,`${rate}万円`],a:0,e:`年間利子＝額面×表面利率＝${face}万円×${rate}％＝${interest}万円です。`,k:'債券利子'});}
 else if(t===5){let w=[20,30,40,50][n%4],r1=[3,4,5,6][n%4],r2=[1,2,3,4][n%4],ans=(w*r1+(100-w)*r2)/100;add({d:'C',s:8,q:`資産Aに${w}％（期待収益率${r1}％）、資産Bに${100-w}％（期待収益率${r2}％）投資する場合、加重平均による期待収益率は何％か。`,c:[`${ans.toFixed(1)}％`,`${(ans+1).toFixed(1)}％`,`${Math.max(0,ans-1).toFixed(1)}％`,`${(r1+r2).toFixed(1)}％`],a:0,e:`${r1}％×${w/100}＋${r2}％×${(100-w)/100}＝${ans.toFixed(1)}％です。`,k:'期待収益率'});}
 else if(t===6){let land=[120,150,180,200,250][n%5],rate=[50,60,70,80][n%4],ans=land*rate/100;add({d:'E',s:2,q:`敷地面積${land}㎡、建ぺい率${rate}％の場合、建築面積の上限は原則何㎡か。`,c:[`${ans}㎡`,`${land}㎡`,`${land-ans}㎡`,`${ans+land/2}㎡`],a:0,e:`${land}㎡×${rate}％＝${ans}㎡です。`,k:'建ぺい率計算'});}
 else if(t===7){let land=[100,120,150,180,200][n%5],rate=[100,150,200,300][n%4],ans=land*rate/100;add({d:'E',s:2,q:`敷地面積${land}㎡、容積率${rate}％の場合、延べ面積の上限は原則何㎡か（他の制限は考慮しない）。`,c:[`${ans}㎡`,`${land}㎡`,`${ans+land}㎡`,`${Math.max(50,ans-land)}㎡`],a:0,e:`${land}㎡×${rate}％＝${ans}㎡です。`,k:'容積率計算'});}
 else if(t===8){let heirs=1+(n%5),ans=3000+600*heirs;add({d:'F',s:3,q:`法定相続人が${heirs}人の場合、相続税の基礎控除額はいくらか。`,c:[`${ans.toLocaleString()}万円`,`${(3000+500*heirs).toLocaleString()}万円`,`${(3000+1000*heirs).toLocaleString()}万円`,`${(600*heirs).toLocaleString()}万円`],a:0,e:`3,000万円＋600万円×${heirs}人＝${ans.toLocaleString()}万円です。`,k:'相続税基礎控除'});}
 else if(t===9){let kids=1+(n%4),den=2*kids;add({d:'F',s:2,q:`配偶者と子${kids}人だけが相続人である場合、法定相続分による子1人当たりの相続分はどれか。`,c:[`1/${den}`,`1/2`,`1/${kids}`,`2/${den}`],a:0,e:`配偶者が1/2、子全体が1/2です。子${kids}人で均等に分けるため、子1人は1/${den}です。`,k:'法定相続分'});}
 else if(t===10){let income=400+(n%8)*50,tax=40+(n%5)*5,social=50+(n%6)*5,ans=income-tax-social;add({d:'A',s:2,q:`年収${income}万円、税金${tax}万円、社会保険料${social}万円の場合、単純化した可処分所得はいくらか。`,c:[`${ans}万円`,`${income-tax}万円`,`${income-social}万円`,`${income}万円`],a:0,e:`可処分所得＝収入－税金－社会保険料＝${income}－${tax}－${social}＝${ans}万円です。`,k:'可処分所得'});}
 else if(t===11){let expense=3000+(n%6)*500,income=1000+(n%5)*300,assets=200+(n%4)*100,ans=expense-income-assets;add({d:'B',s:5,q:`遺族の将来支出見込額${expense.toLocaleString()}万円、将来収入見込額${income.toLocaleString()}万円、充当可能な金融資産${assets}万円の場合、単純化した必要保障額はいくらか。`,c:[`${ans.toLocaleString()}万円`,`${(expense-income).toLocaleString()}万円`,`${(expense-assets).toLocaleString()}万円`,`${expense.toLocaleString()}万円`],a:0,e:`必要保障額＝将来支出－将来収入－充当可能資産＝${expense}－${income}－${assets}＝${ans}万円です。`,k:'必要保障額'});}
 else if(t===12){let start=8000+(n%5)*1000,rate=[5,10,15,20][n%4],end=start*(100+rate)/100;add({d:'C',s:2,q:`投資信託の基準価額が${start.toLocaleString()}円から${end.toLocaleString()}円になった。分配金等を考慮しない単純な上昇率は何％か。`,c:[`${rate}％`,`${rate+5}％`,`${Math.max(1,rate-5)}％`,`${rate*2}％`],a:0,e:`(${end.toLocaleString()}－${start.toLocaleString()})÷${start.toLocaleString()}×100＝${rate}％です。`,k:'投資信託計算'});}
 else if(t===13){let usd=1000+(n%6)*500,fx=[100,110,120,130,140][n%5],ans=usd*fx;add({d:'C',s:5,q:`${usd.toLocaleString()}米ドルを1米ドル＝${fx}円で円換算するといくらか。手数料は考慮しない。`,c:[`${ans.toLocaleString()}円`,`${(usd+fx).toLocaleString()}円`,`${(usd*100).toLocaleString()}円`,`${(ans/10).toLocaleString()}円`],a:0,e:`${usd.toLocaleString()}ドル×${fx}円＝${ans.toLocaleString()}円です。`,k:'外貨換算'});}
 else if(t===14){let sales=1000+(n%6)*500,margin=[5,8,10,12][n%4],profit=sales*margin/100;add({d:'F',s:9,q:`売上高${sales.toLocaleString()}万円、営業利益${profit.toLocaleString()}万円の場合、売上高営業利益率はいくらか。`,c:[`${margin}％`,`${margin+5}％`,`${Math.max(1,margin-3)}％`,`${margin*2}％`],a:0,e:`売上高営業利益率＝営業利益÷売上高×100＝${profit}÷${sales}×100＝${margin}％です。`,k:'経営指標'});}
 else if(t===15){let price=2000+(n%6)*500,rent=[4,5,6,8][n%4],annual=price*rent/100;add({d:'E',s:6,q:`取得価格${price.toLocaleString()}万円の賃貸不動産から年間賃料${annual}万円を得る場合、単純な表面利回りは何％か。`,c:[`${rent}％`,`${rent+2}％`,`${Math.max(1,rent-2)}％`,`${rent*2}％`],a:0,e:`表面利回り＝年間賃料÷取得価格×100＝${annual}÷${price}×100＝${rent}％です。`,k:'不動産利回り'});}
 else if(t===16){let principal=100+(n%6)*50,rate=[1,2,3,4][n%4],interest=principal*rate/100;add({d:'A',s:9,q:`元金${principal}万円を年利${rate}％で1年間借り、単純に元金に年利を掛けて利息を求めると利息はいくらか。`,c:[`${interest}万円`,`${rate}万円`,`${principal+interest}万円`,`${interest*10}万円`],a:0,e:`${principal}万円×${rate}％＝${interest}万円です。`,k:'ローン利息'});}
 else if(t===17){let current=100+(n%5)*50,rate=[1,2,3,4][n%4],future=current*(100+rate)/100;add({d:'A',s:2,q:`${current}万円を年利${rate}％で1年間複利運用した場合、税金等を考慮しない1年後の金額はいくらか。`,c:[`${future}万円`,`${current+rate}万円`,`${current}万円`,`${future+rate}万円`],a:0,e:`${current}万円×(1＋${rate}/100)＝${future}万円です。`,k:'複利計算'});}
 else if(t===18){let totalAssets=5000+(n%5)*1000,equity=totalAssets*[.4,.5,.6,.8][n%4],ratio=equity/totalAssets*100;add({d:'F',s:9,q:`総資産${totalAssets.toLocaleString()}万円、自己資本${equity.toLocaleString()}万円の場合、自己資本比率はいくらか。`,c:[`${ratio}％`,`${100-ratio}％`,`${ratio/2}％`,`${Math.min(100,ratio+20)}％`],a:0,e:`自己資本比率＝自己資本÷総資産×100＝${ratio}％です。`,k:'経営指標'});}
 else {let face=100,rate=[1,2,3,4][n%4],price=[80,90,100,110][n%4],coupon=face*rate/100,ans=coupon/price*100;add({d:'C',s:3,q:`額面100円、表面利率${rate}％の債券を${price}円で購入した場合、直接利回りは何％か。`,c:[`${ans.toFixed(2)}％`,`${rate.toFixed(2)}％`,`${(ans+1).toFixed(2)}％`,`${Math.max(0,ans-1).toFixed(2)}％`],a:0,e:`直接利回り＝年間利子${coupon}円÷購入価格${price}円×100＝${ans.toFixed(2)}％です。`,k:'債券利回り'});}
}
})();